services:
  - type: web
    name: crop-yield-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn modern_dashboard:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0